apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-profile-frontend
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=customer-profile-frontend"
    backstage.io/techdocs-entity: location:default/customer-profile-catalog-info
  links:
    - url: https://customer-profile-frontend.dev-ns-01.tap.welovetap.de
      title: Customer Profile Application
      icon: catalog
spec:
  type: service
  lifecycle: production
  owner: customer-profile-team
  system: customer-profile
  dependsOn: 
    - component:default/customer-profile-frontend
    - resource:default/customer-profile-auth
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-profile-backend
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=customer-profile-backend"
    backstage.io/techdocs-entity: location:default/customer-profile-catalog-info
  links:
    - url: https://customer-profile-frontend.dev-ns-01.tap.welovetap.de
      title: Customer Profile Application
      icon: catalog
spec:
  type: service
  lifecycle: production
  owner: customer-profile-team
  system: customer-profile
  dependencyOf: 
    - component:default/customer-profile-frontend
  dependsOn:
    - resource:default/customer-profile-db
