apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-profile-frontend
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=customer-profile-frontend"
spec:
  type: service
  lifecycle: production
  owner: customer-profile-team
  system: customer-profile
  dependsOn: 
    - component:default/customer-profile-frontend
  links:
    - url: https://customer-profile-frontend.dev-ns-01.tap.dieunkrauts.de
      title: Customer Profile Application
      icon: catalog
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-profile-backend
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=customer-profile-backend"
spec:
  type: service
  lifecycle: production
  owner: customer-profile-team
  system: customer-profile
  dependencyOf: 
    - component:default/customer-profile-frontend