apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ricket-son
spec:
  profile:
    displayName: Erik Kaisler
    email: erikkaisler@gmail.com
  memberOf: ["operators", "developers", "customer-profile-team"]
